### ISSUE TITLE
mysql crash

### ISSUE THREAD

**Issue by mkabischev** [tony2001/pinba_engine#37]
Hi.

I installed mysql 5.5 and pinba. Also i installed pinboard and when it does aggregation mysql crashes. I enabled full mysql log and found query causes crash:
```
INSERT INTO ipm_timer
                        (timer_id, request_id, hit_count, value, tag_name, tag_value, created_at)
                    SELECT
                        t.id, t.request_id, t.hit_count, t.value, tag.name as tag_name, tt.value as tag_value, '2015-01-16 21:38:23'
                    FROM
                        timer t
                    JOIN
                        timertag tt ON tt.timer_id = t.id
                    JOIN
                        tag ON tt.tag_id = tag.id
                    WHERE
                        t.request_id IN (0, 1, 3);
```

I tried to make it simple and that`s result:
```
SELECT
    *
FROM
    timer t
JOIN
    timertag tt ON tt.timer_id = t.id
JOIN
    tag ta ON tt.tag_id = ta.id;
```

Also i`ve go same error with percona 5.6

Pinba version: master

**Comment by muxx** [comment]
At this https://github.com/intaro/pinboard#installation I wrote that you should use `devel` branch of pinba with Pinboard

**Comment by mkabischev** [comment]
@muxx, i know. But i can`t compile devel branch. There is no file pinba_limits.h, but it`s required since 6c726257ce28cbfe0799deb3de651377d7cc5a03 commit.

**Comment by muxx** [comment]
On `master` branch pinba timers don't work correctly.

**Comment by mkabischev** [comment]
Can you suggest commit from devel working properly?

**Comment by muxx** [comment]
O wrote #27 at May 19, 2014. Actual commit on those period were 5df9ba091e3ef531dfed1802d8afc3012e275002.

**Comment by mkabischev** [comment]
@muxx, looks like it works. Thank you!

**Comment by tony2001** [comment]
Thanks for the reminder, I've added the missing file.
