### ISSUE TITLE
p95 value is 0

### ISSUE THREAD

**Issue by tuannat** [tony2001/pinba_engine#46]
I create report table like this:

```
CREATE TABLE `tag_info_category_server_name` (
  `tag1_value` varchar(64) DEFAULT NULL,
  `tag2_value` varchar(64) DEFAULT NULL,
  `req_count` int(11) DEFAULT NULL,
  `req_per_sec` float DEFAULT NULL,
  `hit_count` int(11) DEFAULT NULL,
  `hit_per_sec` float DEFAULT NULL,
  `timer_value` float DEFAULT NULL,
  `timer_median` float DEFAULT NULL,
  `index_value` varchar(256) DEFAULT NULL,
  `p90` float DEFAULT NULL,
  `p95` float DEFAULT NULL,
  `p99` float DEFAULT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='tagN_info:category,__server_name::90,95,99';
```

but the value of p95 is always 0.

**Comment by tony2001** [comment]
That's because there are two more fields between timer_median and index_value:
    `ru_utime_value` float DEFAULT NULL,
    `ru_stime_value` float DEFAULT NULL,

There's a helper script that generates reports, I'll add it to the next release tarball.
For now you can check it out from Git, it's in the scripts/ subdirectory.

**Comment by tuannat** [comment]
It's working now, thank you very much
