### ISSUE TITLE
unrecognized option: --with-hoard

### ISSUE THREAD

**Issue by tmcdos** [tony2001/pinba_engine#52]
README asserts that Pinba can be compiled with Hoard. However, latest configure script does not recognize the option "--with-hoard" and the source code of Pinba does not contain references to any of the Hoard functions.

**Comment by pmontepagano** [comment]
Check a9dd9d337bee8a9a6cea73d5d7d2f9e7dcbf332b and 23a0f445d215b595ece5f4a1f3604677375bbf8a .

**Comment by tony2001** [comment]
Right, you can use Hoard or jemalloc (or any other memory allocator) with LD_PRELOAD, it's easy and doesn't require any configure options.
